name: 自动推送代码

on:
  # 定时触发
  schedule:
    - cron: '0 */6 * * *'  # 每6小时执行一次
  
  # 手动触发
  workflow_dispatch:

jobs:
  push-to-github:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: 配置Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: 检查并提交更改
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "自动提交: $(date +'%Y-%m-%d %H:%M:%S')"
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "没有变更需要提交"
          fi 